---
name: William (Hank) 
surname: Murrah
position: "Associate Professor and Department Head"
address: "College of Education, Auburn University"
# profilepic: profileSmall.jpg
phone: 334-844-3806
www: statistical-thinking.com
email: "wmm0017@auburn.edu"
twitter: EdStat
github: wmmurrah
linkedin: wmmurrah
headcolor: 333335 #E87722 # black = 000000
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education
 
## Ph.D. Educational Psychology, University of Virginia, 2010.
## M.Ed. Community and Agency Counseling, University of Montevallo, 1998.
## B.S. Psychology,  University of Montevallo, 1993.
  
# Current Position

**Department Head**, *Department of Educational Foundations, Leadership, and Technology*, College of Education, **Auburn University**, 2023-present.

**Associate Professor**, *Educational Research, Measurement, and Assessment Program, Educational Foundations, Leadership, & Technology*, **Auburn University** , 2021-present.

**Assistant Professor**, *Educational Research, Measurement, and Assessment Program, Educational Foundations, Leadership, & Technology*, **Auburn University** , 2016-2021.

**Research Scientist**, *University of Virginia*, Charlottesville, VA, 2013-2016.

**Postdoctoral Fellow**, *University of Virgina*, Charlottesville, VA, 2010-2013.

# Research

## Publications
 \* indicates collaboration with students.

Agostinelli, P. J., Bordonie, N. C., Linder, B. A., Robbins, A. M., Jones, P. L., Reagan, L. F., Mobley, C. B., Miller, M. W., **Murrah, W. M.**, & Sefton, J. M. (2025). Acute exercise impacts heart rate variability but not cognitive flexibility during subsequent simulated firefighter occupational tasks. *European Journal of Applied Physiology*, 125(4), 1037–1048. https://doi.org/https://doi.org/10.1007/s00421-024-05650-9

Agostinelli, P. J., Bordonie, N. C., Linder, B. A., Robbins, A. M., Jones, P. L., Reagan, L. F., Mobley, C. B., Miller, M. W., **Murrah, W. M.**, & Sefton, J. M. (2025). The Effect of Fitness on Performance, Exertion, and Cognition During Simulated Firefighter Occupational Tasks. Journal of Functional Morphology and Kinesiology, 10(2), 129. https://doi.org/10.3390/jfmk10020129

Pendola, A., Appiah, J., **Murrah, W.**, & Beavers, C. (2025). Strategies for efficacy and belongingness towards foundational STEM skills for at-promise graduate students: The QMER  learning community. *Current Issues in Education*, 26(1).
https://doi.org/10.14507/cie.vol26iss1.2260
 
Brinkerhoff, S.A., Sánchez, N.,  Culver, M.N., **Murrah, W.M.**, Robinson, A.T., McCullough, J.D., Miller, M.W., Roper, J.A. (2024). The dual timescales of gait adaptation: initial stability adjustments followed by subsequent energetic cost adjustments. *Journal of Experimental Biology, 227 (23): jeb249217. doi: https://doi.org/10.1242/jeb.249217

Monaghan, P.G., **Murrah, W.M.**, Neely, K.A. et al. Exploring age-related differences in the relationship between spatial and temporal contributions to step length asymmetry during split-belt adaptation. Experimental Brain Research 242, 2815–2825 (2024). https://doi.org/10.1007/s00221-024-06929-1

\* Agostinelli P.J., Bordonie, N.C., Robbins. A.M., Jones. P.L., Reagan. L.F., Mobley. C.B., Miller. M.W., **Murrah, W.M.**, Sefton, J.M. (2025) Impact of acute exercise on performance and physiological stress during simulated firefighter occupational tasks. *Scientific Reports* v14(1):29778. doi:10.1038/s41598-024-81015-8. PMID: 39616210; PMCID: PMC11608254.

\* Agostinelli, P.J., Bordonie, N.C., Linder, B.A., Robbins, A.M., Jones, P.L., Reagan, L.F., Mobley, C.B., Miller, M.W., **Murrah, W.M.**, Sefton, J.M. (2024) Acute exercise impacts heart rate variability but not cognitive flexibility during subsequent simulated firefighter occupational tasks. Eur J Appl Physiol. 2025 Apr;125(4):1037-1048. doi: 10.1007/s00421-024-05650-9. Epub 2024 Nov 13. PMID: 39537898; PMCID: PMC11950049. 

Monaghan, P.G., **Murrah, W.M.**, Walker, H.C. et al. Cognitive-motor interference in people with essential tremor. *Scientific Reports, 14, 23456 (2024). https://doi.org/10.1038/s41598-024-74310-x

 Bacelar, M.F.B, Parma,  J. O., **Murrah, W.M.**, & Miller, M.W. (2024). Meta-analyzing enhanced expectancies on motor learning: Positive effects but methodological concerns. *International Review of Sport and Exercise Psychology*, 17(1), 587-616. https://www.tandfonline.com/action/showCitFormats?doi=10.1080/1750984X.2022.2042839
 
\* Agostinelli, P., Bordonie, N., Linder, B., Robbins, A., Jones, P., Reagan, L., Mobley, C. B., MIller, M., **Murrah, W. M.**, & Sefton, J. E. (2024). The impact of training status on firefighter task performance after acute exercise. Physiology, 39(S1). https://doi.org/10.1152/physiol.2024.39.s1.870
 
\* Bordonie, N., Agostinelli, P., Linder, B., Robbins, A., Jones, P., Reagan, L., Mobley, C. B., Miller, **M., Murrah, W. M.**, & Sefton, J. (2024). Impact of anaerobic fitness on performance and physiology during simulated firefighting tasks. Physiology, 39(S1). https://doi.org/10.1152/physiol.2024.39.s1.2060
 
 \* Monaghan, P. G., **Murrah, W. M.**, Walker, H. C., Neely, K. A., & Roper, J. A. (2024). Evaluating postural transition movement performance in individuals with essential tremor via the instrumented timed up and go. *Sensors*, 24(7), 2216. https://doi.org/10.3390/s24072216.
 
 Giordano, K. A., Barrack, A. J., **Murrah, W. M.**, Karduna, A. R., Michener, L. A., & Wasserberger, K. W. (2024). Usage and acceptability of data normalization in baseball pitching. *Sports Biomechanics*, 1–12. https://doi.org/10.1080/14763141.2024.2302830
 
 Grissmer, D., Buddin, R., Berends, M., White, T.G., Willingham, D.T., Decoster, J., Duran, Chelsea, A.K., Hulleman, C.S., **Murrah, W. M.**, Evans, T. (2024). How Building Knowledge Boosts Literacy and Learning First causal study finds outsized impacts at “Core Knowledge” schools. *Education Next*, 24(2), 52-56.
 
 \* Rightmire, Z. B., Agostinelli, P. J., **Murrah, W. M.**, Roper, J. A., Roberts, M. D., & Sefton, J. M. (2024). Acute high-intensity interval training improves esport performance in super smash brothers ultimate competitors. *Journal of Electronic Gaming and Esports*, 2(1). https://doi.org/10.1123/jege.2023-0031.
 
\* Agostinelli, P. J., Bordonie, N. C., Robbins, A. M., Jones, P. L., Reagan, L. F., Mobley, C. B., Miller, M. W., **Murrah, W. M.**, & Sefton, J. M. (2024). The effect of two acute exercise modalities on physiology and condition during firefighter occupational tasks. *International Journal of Exercise Science: Conference Proceedings*, 16. https://digitalcommons.wku.edu/ijesab/vol16/iss3/1 
 
 \*Zou, C., Zhao, Y., Garza, K. B., Hollingsworth, J. C., **Murrah, W. M.**, Westrick, S., & Fox, B. I. (2023). Text message interventions for physical activity among university students: a systematic review and meta-analysis. *American Journal of Pharmaceutical Education*, 87(8), 100538. https://doi.org/10.1016/j.ajpe.2023.100538
 
 \* Brinkerhoff, S. A., **Murrah, W. M.**, & Roper, J. A. (2023). The relationship between gait speed and mediolateral stability depends on a person’s preferred speed. *Scientific Reports*, 13(1). https://doi.org/10.1038/s41598-023-32948-z

\*Lyons, K.D., Parks, A.G., Dadematthews, O.D., Zandieh, N.L.,  McHenry P.A., Games K.E., Goodlett M.D., **Murrah W.M.**, Roper J.A., Sefton, J.M. (2023). Core and Whole-Body Vibration Exercise Improve Military Foot March Performance in Novice Trainees: A Randomized Controlled Trial. *Military Medicine* 188 (1-2), e254-e259. https://doi.org/10.1093/milmed/usab294

\*Brinkerhoff, S.A., Mathew, G.M., **Murrah, W.M.**, Chang, A.M., Roper, J.A., Neely, K.A. (2022). Sleep restriction impairs visually and memory-guided force control. *PlOS One*, 17 (9), e0274121. https://doi.org/10.1371/journal.pone.0274121 

\*Larsen, J., Roper, J., **Murrah, W.M.**, & Zabala, M. (2022). Cognitive dual-task alters Local Dynamic Stability of lower extremity during common movements. *Journal of Bioimechanics*, 137, 111077. https://doi.org/10.1016/j.jbiomech.2022.111077

\*Parks A.G., **Murrah W.M.**, Weimar W.H., McHenry P.A., Bigham D., Giordano K., Sefton J.M.(2023) Impact of Two Types of Fitness Programs on Soldier Physical Fitness. *International Journal of Exercise Science. 15(4):1326-1346. doi: 10.70252/YBTF2692. PMID: 36582397; PMCID: PMC9762245.

\*Lyons, K. D., Parks, A. G., Dadematthews, O., Zandieh, N., McHenry, P., Games, K. E., Goodlett, M. D., **Murrah, W.**, Roper, J., & Sefton, J. M. (2021). Core and Whole Body Vibration Exercise Influences Muscle Sensitivity and Posture during a Military Foot March. International Journal of Environmental Research and Public Health, 18(9), 4966. https://doi.org/10.3390/ijerph18094966

Frugé, A. D., Smith, K. S., Riviere, A. J., Tenpenny-Chigas, R., Demark-Wahnefried, W., Arthur, A. E., **Murrah, W. M.**, van der Pol, W. J., Jasper, S. L., Morrow, C. D., Arnold, R. D., & Braxton-Lloyd, K. (2021). A Dietary Intervention High in Green Leafy Vegetables Reduces Oxidative DNA Damage in Adults at Increased Risk of Colorectal Cancer: Biological Outcomes of the Randomized Controlled Meat and Three Greens (M3G) Feasibility Trial. *Nutrients*, 13(4), 1220. https://doi.org/10.3390/nu13041220

**Murrah, W. M.** (2019). Compound Bias due to Measurement Error When Comparing Regression Coefficients. Educational and Psychological Measurement, 80(3), 548-577. https://doi.org/10.1177/0013164419874494 

**Murrah, W. M.** (2020). Compound Bias Due to Measurement Error When Comparing Regression Coefficients, *Educational and Psychological Measurement*, 80(3).

\*Oldfather, T., Zabala, M., Goodlett, M., and **Murrah, W.** (2020). Knee Valgus Versus Knee Abduction Angle: Comparative Analysis of Medial Knee Collapse Definitions in Female Athletes. Journal of Biomechanical Engineering*, December 2020; 142(12): 121002. https://doi.org/10.1115/1.4047549

Chesser, S., **Murrah, W.**, & Forbes, S. A. (2020). Impact of Personality on Choice of Instructional Delivery and Students' Performance. *American Journal of Distance Education*, 34(3), 211-223. https://doi.org/10.1080/08923647.2019.1705116

Frugé, A. D., Smith, K. S., Riviere, A. J., Demark-Wahnefried, W., Arthur, A. E., **Murrah, W. M.**, Morrow, C. D., Arnold, R. D., & Braxton-Lloyd, K. (2019). Primary Outcomes of a Randomized Controlled Crossover Trial to Explore the Effects of a High Chlorophyll Dietary Intervention to Reduce Colon Cancer Risk in Adults: The Meat and Three Greens (M3G) Feasibility Trial. *Nutrients*, 11(10), 2349. https://doi.org/10.3390/nu11102349

\*Friesen, K. B. Barfield, J.W. **Murrah, W.M.**, Dugas, J.R. Andrews, J.R. and Oliver, G.D. (2019).The Association of Upper-Body Kinematics and Earned Run Average of National Collegiate Athletic Association Division I Softball Pitchers,	*Journal of Strength and Conditioning*, 35(11):p 3145-3150, November 2021. DOI: 10.1519/JSC.0000000000003287

\*Brinkerhoff, S. A., **Murrah, W. M.** Hutchison, Z. Miller, M. Roper, J. A. (2019). 	Words matter: Instructions dictate "self-selected" walking speed in young adults. *Gait & Posture* 95 (June). 223-226. doi: 10.1016/j.gaitpost.2019.07.379

Brock, L. L., **Murrah, W. M.**, Cottone, E. A., Mashburn, A. J., & Grissmer, D. W. (2018). An after-school intervention targeting executive function and visuospatial skills also improves classroom behavior. *International Journal of Behavioral Development*.  

**Murrah, W. M.**, Kosovich, J. J., & Hulleman, C. S. (2016). Measuring Fidelity in Educational Settings. In Roberts, G., Vaughn, S., Beretvas, T., & Wong, V. (Eds.), *Implementation Fidelity in Randomized Educational Trials: An Applied Perspective.* Routledge.

Cameron, C. E., Cottone, E. A., **Murrah, W. M.** & Grissmer, D. W. (2016). How are motor skills linked to children's school performance and academic achievement? *Child Development Perspectives, 10(2)*, 93-98.

\*Kim, H., Schmidt, K. M., **Murrah, W. M.**, Cameron, C. E., & Grissmer, D. (2015). A Rasch Analysis of the KeyMath-3 Diagnostic Assessment. *Journal of Applied Measurement*, 16(4), 365-378.

\*Kim, H., **Murrah, W. M.**, Cameron, C. E., Brock, L. L., Cottone, E. A., & Grissmer, D. (2014). Psychomotor properties of the Teacher-Reported Motor Skills Rating Scale. *Journal of Psychoeducational Assessment*, first published on October 6, 2014 as doi:10.1177/0734282914551536.

Ponitz, C. C., Brock, L. L., **Murrah, W. M.**, Bell, L., Worzalla, S., Grissmer, D. W., & Morrison, F. J. (2012). Fine motor skills and executive function both contribute to kindergarten achievement. *Child Development*, 83(4), 1229-1244.

Grissmer, D., Grimm, K.J., Aiyer, S.M., **Murrah, W. M.**, & Steele, J.S. (2010). Fine motor skills and early comprehension of the world: Two new school readiness indicators. *Developmental Psychology*, 46(5), 1008-1017.

## Presentations

**Murrah, W.M.**, Chesser, S., Neugebauer, N.M. (2022). *Nonlinear Gompertz Curves of Mathematics, Reading, and Science Achievement*, Presented at the American Educational Research Association Annual Meeting.

\* Moore, T.F., Chesser, S., **Murrah, W.M.** (2022), *Improving Connectedness in At-Risk Adolescents in the Alternative School Setting*, Poster presented at the American Educational Research Association Annual Meeting.

\*Neely, K., Zhang, Z., Blanton, R., Gladson,  M., Schmid, D. Heavlin, H., Brown, S., Brown, S., Pangelinan, M.,  **Murrah, W. M.** (2022). *Balance Control in Midlife Adults With and Without ADHD.* Presented at North American Society for the Psychology of Sport and Physical Activity. 

\*Baelar, M.F.B., Parma, J.O., **Murrah, W.M.**, Miller, M. (2021). Meta-Analysis of Enhanced Expectancies in Motor Learning. *Journal of Sport & Exercise Psychology* Volume: 43 (2021) ISSN: 0895-2779 Online ISSN: 1543-2904

\*Neely, K., Zhang, Z., & **Murrah, W. M.** (2021) *Variability in Motor Control: Multilevel Modeling Reveals Meaningful Differences in Force Output.* Presented at North American Society for the Psychology of Sport and Physical Activity Virtual Conference.

Schmid, D., Blanton, R., White, T., **Murrah, W. M.**, & Kneely, K. (2021). *Withdrawn Behavior Influences Engagement in Vigorous and Moderate Physical Activity*. Presented at the North American Society for the Psychology of Sport and Physical Activity Virtual Conference.

Francis, M., Tibbetts, Y., **Murrah, W. M.**, Phelps, J., Silverman, D., Moran, M., Kosovich, J., & Hulleman, C. (2018) *Using a utility-value intervention to remove barriers in gateway math courses.* Poster presented at the 2018 Understanding Interventions Conference, Baltimore, MD.

**Murrah, W. M.**, Ruzek, E. A., & Grissmer, D. W. (2017) *Children's fine motor skills are important for school readiness and science achievement.* Symposium presented at the Society for Research in Child Development 2017 Biennial Meeting, Austin, TX. 

**Murrah, W. M.**(2015) *The Relative Importance of School Readiness Skills as Predictors of First, Third, and Eighth Grade Achievement*. Poster presented at the Society for Research in Child Development Biennial Meeting, Philadelphia, PA.

**Murrah, W. M.**, Grissmer, D., Ko, Michelle, Player, D., Cabell, S., O'Brien, R. H.(2015). *Early achievement impacts of Core Knowledge charter schools on early comprehension and general knowledge through 1st grade.* Presented at Association for Education Finance and Policy Annual Conference. Washington, DC.

**Murrah. W. M.** (2013) *The evolution and evaluation of a play-based, after-school curriculum that improves executive function, visuospatial and math skills for disadvantaged children.* Organizer of seminar and presenter at the Society for Research on Educational Effectiveness Fall Conference. Washington, DC.

**Murrah. W. M.** (2011). *Explaining the association between fine motor skills and math achievement.* Seminar presented to the faculty and students of the developmental psychology department at the University of Virginia. Charlottesville, VA

**Murrah. W. M.** (2011). *Fine motor skills predict later math, science, and reading achievement*. Symposium presented at the Society for Research in Child Development 2011 Biennial Meeting, Montreal, Quebec.

**Murrah. W. M.** (2010). *Fine motor skills as a predictor of later math, reading, and science elementary achievement.* Paper presented to the Conference on Human Development, 2010 Annual Meeting, New York City, NY.

**Murrah. W. M.** (2009). *Which developmental skills predict later math, reading, and science elementary school achievement?* Paper presented to National Science Foundation Advisory Board, 2009. Charlottesville, VA.

# Grant Funding

## Previous Funding

Inhibitory Motor Control in Adults with ADHD, PI: Kristina Neely, *Auburn University Intramural Grants Program*. $25,000;  Role: Co-investigator.

How the Motor System Reflects Impulsivity and Inhibitory Control in Healthy Young Adults. PI: Kristina Neely. *Auburn University Intramural Grants Program*. $20,600. Role: Co-PI.

Removing Barriers to Success in Mathematics: An Integrative Expectancy-Value Intervention. PI: Chris Hulleman. *National Science Foundation*. Approximately $1,500,000. Project Period: 9/01/2015 - 8/31/2019. Role: Senior Personnel/Methodologist.

Developmental Skills Linked to Math and Science Achievement: An Interdisciplinary Data-Intensive Approach to Identification and Improvement through Experimental Intervention. *National Science Foundation*. Approximately $2,500,000. Project Period: 9/1/2013 - 8/31/2018. Role: Research Scientist/Methodologist.

Evaluation of Core Knowledge charter schools in Colorado. *Institute of Education Sciences*. Approximately $4,900,000. Project Period: 07/01/2009 - 12/31/2015. Role: Research Scientist/Methodologist.

Efficacy of the WINGS after-school social and emotional learning (SEL) program. *Institute of Education Sciences*. Approximately $2,700,000. Project Period: 09/01/2011 - 8/31/2015. Role: Research Scientist/Methodologist. 

Math and science achievement gaps for minority and disadvantaged students: Developmental and environmental influences from nine months to 8th grade, *National Science Foundation*, 2008 - 2012 ($952,710) Role: Co-Investigator/ Methodologist.

Improving fine motor skill development to promote mathematical ability, *Institute of Education Sciences*, 2009 - 2012 ($462,765) Role: Primary Data Analyst

New kindergarten readiness indicators for math and science: Next steps in validation, communication and projecting policy impacts, *National Science Foundation*, 2010-2012 ($297,653) Role: Co-investigator/Methodologist. 

## Other Research Experience

Research Associate, *University of Virginia*, Summer 2010--Spring 2014.

Graduate Research Assistant, *University of Virginia*, Summer 2009--Spring 2010.

Curry Participant Pool Coordinator, *University of Virginia*, Summer 2008- Spring 2009.

Graduate Research Assistant, *University of Virginia*, 2005-2006.

# Teaching

Special Topics: Multilevel Modeling, ERMA 7970, *Auburn University *Summer 2020.
 
Advanced Measurement Theory, ERMA 8350, *Auburn University*, 2022 - 2023.

Introduction to Structural Equation Modeling, ERMA 8340, *Auburn University*, 2019 - 2022.

Design and Analysis III, ERMA 8320, *Auburn University*, 2018 - 2022.

Design and Analysis II, ERMA 7310, *Auburn University*, 2018 - 2023.

Design and Analysis I, ERMA 7300, *Auburn University*, 2017 - 2023.

Basic Methods in Education Research, ERMA 7200, *Auburn University*, 2016 - 2021.

Confirmatory Factor Analysis and Scale Reliability, Statistical Programming Workshop, University of Virginia, January, 2016.

Introduction to Multiple Imputation with the `mice` package, Statistical Programming Workshop, University of Virginia, October, 2015.

Introduction to Multilevel Modeling, Statistical Programming Workshop, FOCAL Lab, University of Virginia, July, 2015. 

Introduction to Statistical Programming with R, Statistical Programming Workshop, University of Virginia, Spring, 2015.

Introduction to Linear Models, University of Virginia, Curry Summer Undergraduate Research Program, Summer 2012.

Introduction to Inferential Statistics, University of Virginia, Curry Summer Undergraduate Research Program, Summer 2011.

Child Development, co-instructor, University of Virginia, Spring 2008.

Child Development, teaching assistant, University of Virginia, 2006-2007.

Child Development, co-instructor, Hampton Roads Center, University of Virginia, Spring 2005.

## Professional Activities


Editorial Board for *Interdisciplinary Education and Psychology*.

Reviewer for *Child Development*

Reviewer for *Journal of Abnormal Child Psychology* 

Reviewer for *Early Childhood Research Quarterly* 

Member, *American Statistical Association *

Member, *Society for Research in Child Development*

Member, *American Educational Research Association*

## Invited Workshops

SREE Workshop: Intervention Fidelity -Models, Methods, and Applications, Fall 2014


## Trainings and Conferences Attended

Intensive Longitudinal Methods, Statistical Horizons, October 23-24, 2015

Mediation, Moderation, and Conditional Process Analysis, Andrew F. Hayes, University of Virginia, June 4-5, 2015  

Institute of Education Sciences Summer Research Training Institute: Cluster-Randomized Trials, Northwestern University, July 15-26, 2012

UseR! 2012, Vanderbilt University, June 11-15, 2012

Functional MRI in Clinical Research and Practice: Measurement, Design and Analysis, Carnegie Mellon University/University of Pittsburgh, June 13-17, 2011

Missing Data Workshop, University of Virginia, June 1-7, 2011

Society for Research in Child Development Conference, Montreal, March 31-April 3, 2011

Multi-Modal Neuroimaging Training, Martinos Medical Center, Boston, December 13-17, 2010

Conference on Human Development, New York, April 9-12, 2010


## Software Proficiency

R, Mplus, \LaTeX, SPSS, Python, Stan, JAGS

# Other  Professional Experience

Team Building Coordinator, *Charlottesville's Challenge Course*, Charlottesville, VA, 2002 - 2004.

Counselor/Intervention Specialist, *Hoover City School System*, Hoover, AL, 1999 - 2002.

Bridges Drug Education Program Instructor, *Hoover City School System*, Hoover, AL, 1999 - 2002.

Independent Contract Work, *Central Alabama*, 1997 - 2002.

Adventure Based Counselor/Case Manager, *Bradford Health Services*, Pelham, AL, 1995 - 1997.

Conflict Resolution Counselor, *Jemison Boy's Ranch*, Jemison, AL, 1993 - 1995.
