---
title: "CV"
author: "William M. Murrah"
email: wmm0017@auburn.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: ~/Templates/wmm-latex-cv.tex
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
github: wmmurrah
jobtitle: ' Assistant Professor, Educational Research, Measurement, and Analysis
  Program'
keywords: education, educational psychology
linkcolor: blue
fontawesome: yes
phone: 334/844-3806
address: Auburn University, Auburn AL 36849
updated: no
urlcolor: blue
web: statistical-thinking.com
---

# Education
 
## Ph.D. Educational Psychology, University of Virginia, 2010.

* Dissertation: Comparing self-regulatory and early academic skills as predictors of later math, reading, and science elementary school achievement.
  
* Co-chairs: David W. Grissmer, Herbert C. Richards.
       
## M.Ed. Community and Agency Counseling, University of Montevallo, 1998.
## B.S. Psychology,  University of Montevallo, 1993.
  
# Current Position

* **Assistant Professor**, *Educational Research, Measurement, and Assessment Program, Educational Foundations, Leadership, & Technology*, **Auburn University** , 2016-present.

# Research
 
## Publications
 \* indicates collaboration with students.

**Murrah, W M.** (2020) Compound Bias Due to Measurement Error When Comparing Regression Coefficients. *Educational and Psychological Measurement* 80(3), 548-577.

Chesser, S. S, **Murrah, W. M.**, Forbes, S. A. (2020). Impact of personality and choice of instructional media on students' performance in online and face-to-face courses, *Computers in Human Behavior*.

\*Brinkerhoff, S. A.,**Murrah, W. M.**,  Hutchison, Z., Miller, M., & Roper, J. A. (2019) 
Words matter: Instructions dictate "self-selected" walking speed in young adults. *Gait & Posture*.

Frug'e, A.D., \*Smith, K.S., Riviere, A.J., Demark-Wahnefried, W.,  Arthur, A.E., **Murrah, W.M.**,  Morrow, C.D.,  Arnold, R.D. & Braxton-Lloyd, K. (2019). Primary outcomes of a randomized controlled crossover trial to explore the effects of a high chlorophyll dietary intervention to reduce colon cancer risk in adults: The Meat and Three Greens (M3G) Feasibility Trial. *Nutrients* 11(10), 2349.

\*Friesen, K. B., Barfield, J. W., **Murrah, W. M.**, Dugas, J. R., Andrews, J. R., & Oliver, G. D. (2019). The association of upper body kinematics and ERA of National Collegiate Athletics Association Division I softball pitchers. *Journal of Strength and Conditioning Research*.

Brock, L. L., **Murrah, W. M.**, Cottone, E. A., Mashburn, A. J., & Grissmer, D. W. (2017). An after-school intervention targeting executive function and visuospatial skills also improves classroom behavior. *International Journal of Behavioral Development*.  

**Murrah, W. M.**, Kosovich, J. J., & Hulleman, C. S. (2016). Measuring Fidelity in Educational Settings. In Roberts, G., Vaughn, S., Beretvas, T., & Wong, V. (Eds.), *Implementation Fidelity in Randomized Educational Trials: An Applied Perspective.* Routledge.

Cameron, C. E., Cottone, E. A., **Murrah, W. M.** & Grissmer, D. W. (2016). How are motor skills linked to children's school performance and academic achievement? *Child Development Perspectives, 10(2)*, 93-98.

\*Kim, H., Schmidt, K. M., **Murrah, W. M.**, Cameron, C. E., & Grissmer, D. (2015). A Rasch Analysis of the KeyMath-3 Diagnostic Assessment. *Journal of Applied Measurement*, 16(4), 365-378.

\*Kim, H., **Murrah, W. M.**, Cameron, C. E., Brock, L. L., Cottone, E. A., & Grissmer, D. (2014). Psychomotor properties of the Teacher-Reported Motor Skills Rating Scale. *Journal of Psychoeducational Assessment*, first published on October 6, 2014 as doi:10.1177/0734282914551536.

Ponitz, C. C., Brock, L. L., **Murrah, W. M.**, Bell, L., Worzalla, S., Grissmer, D. W., & Morrison, F. J. (2012). Fine motor skills and executive function both contribute to kindergarten achievement. *Child Development*, 83(4), 1229-1244.

Grissmer, D., Grimm, K.J., Aiyer, S.M., **Murrah, W. M.**, & Steele, J.S. (2010). Fine motor skills and early comprehension of the world: Two new school readiness indicators. *Developmental Psychology*, 46(5), 1008-1017.

## Publications in Press
\* indicates collaboration with students.

\*Wright, T. K., **Murrah, W. M.**, Zabala M. E. (in press). Knee Valgus vs. Knee Abduction Angle: Comparative Analysis of Medial Knee Collapse Definitions in Female Athletes, *Journal of Biomechanical Engineering*.

## Publications in Preparation
\* indicates collaboration with students.

**Murrah. W. M.**, Frances, M., Silverman, D., Hulleman, C. S. (in preparation). Student trajectories through front-door math courses in community college.

Hulleman, C. S., Tibbetts, Y., **Murrah, W. M.** (in preparation). Impacts of a utility value intervention among community college students in front-door math courses.

Hulleman, C. S., Lee, M.,**Murrah, W. M.** et al. (in preparation). From politics to hurricanes: Lessons learned from a research-practice partnership focused on improving motivation in community college math. 


## Presentations

Francis, M., Tibbetts, Y., Murrah, W. M., Phelps, J., Silverman, D., Moran, M., Kosovich, J., & Hulleman, C. (2018) *Using a utility-value intervention to remove barriers in gateway math courses.* Poster presented at the 2018 Understanding Interventions Conference, Baltimore, MD.

Murrah, W. M., Ruzek, E. A., & Grissmer, D. W. (2017) *Children's fine motor skills are important for school readiness and science achievement.* Symposium presented at the Society for Research in Child Development 2017 Biennial Meeting, Austin, TX. 

Murrah, W. M.(2015) *The Relative Importance of School Readiness Skills as Predictors of First, Third, and Eighth Grade Achievement*. Poster presented at the Society for Research in Child Development Biennial Meeting, Philadelphia, PA.

Murrah, W. M., Grissmer, D., Ko, Michelle, Player, D., Cabell, S., O'Brien, R. H.(2015). *Early achievement impacts of Core Knowledge charter schools on early comprehension and general knowledge through 1st grade.* Presented at Association for Education Finance and Policy Annual Conference. Washington, DC.

Murrah. W. M. (2013) *The evolution and evaluation of a play-based, after-school curriculum that improves executive function, visuospatial and math skills for disadvantaged children.* Organizer of seminar and presenter at the Society for Research on Educational Effectiveness Fall Conference. Washington, DC.

Murrah. W. M. (2011). *Explaining the association between fine motor skills and math achievement.* Seminar presented to the faculty and students of the developmental psychology department at the University of Virginia. Charlottesville, VA

Murrah, W. M. (2011). *Fine motor skills predict later math, science, and reading achievement*. Symposium presented at the Society for Research in Child Development 2011 Biennial Meeting, Montreal, Quebec.

Murrah, W. M. (2010). *Fine motor skills as a predictor of later math, reading, and science elementary achievement.* Paper presented to the Conference on Human Development, 2010 Annual Meeting, New York City, NY.

Murrah, W. M. (2009). *Which developmental skills predict later math, reading, and science elementary school achievement?* Paper presented to National Science Foundation Advisory Board, 2009. Charlottesville, VA.


# Grant Funding

## Current Funding

Auburn University National Alumni Council Grant Educational Learning Community Improvement. PI: Andrew Pendola. $1,617. Grant to support QMER Workshop development and implementation.

## Pending Funding

Strategic Teams Engaging in Meaningful Learning & Leadership (STEM-L2). PI: Victoria Cardullo. *National Science Foundation*. Approximately 1,500,000. Project Period 9/01/2021 - 8/31/2025. Role: Co-Investigator.

## Previous Funding

  Removing Barriers to Success in Mathematics: An Integrative Expectancy-Value Intervention. PI: Chris Hulleman. *National Science Foundation*. Approximately $1,500,000. Project Period: 9/01/2015 - 8/31/2019. Role: Senior Personnel/Methodologist.
  
Developmental Skills Linked to Math and Science Achievement: An Interdisciplinary Data-Intensive Approach to Identification and Improvement through Experimental Intervention. *National Science Foundation*. Approximately $2,500,000. Project Period: 9/1/2013 - 8/31/2018. Role: Research Scientist/Methodologist.

Evaluation of Core Knowledge charter schools in Colorado. *Institute of Education Sciences*. Approximately $4,900,000. Project Period: 07/01/2009 - 12/31/2015. Role: Research Scientist/Methodologist.

Efficacy of the WINGS after-school social and emotional learning (SEL) program. *Institute of Education Sciences*. Approximately $2,700,000. Project Period: 09/01/2011 - 8/31/2015. Role: Research Scientist/Methodologist. 

Math and science achievement gaps for minority and disadvantaged students: Developmental and environmental influences from nine months to 8th grade, *National Science Foundation*, 2008 - 2012 ($952,710) Role: Co-Investigator/Methodologist.

Improving fine motor skill development to promote mathematical ability, *Institute of Education Sciences*, 2009 - 2012 ($462,765) Role: Primary Data Analyst

New kindergarten readiness indicators for math and science: Next steps in validation, communication and projecting policy impacts, *National Science Foundation*, 2010-2012 ($297,653) Role: Co-investigator/Methodologist. 

## Other Research Experience

Research Associate, *University of Virginia*, Summer 2010--Spring 2014.

Graduate Research Assistant, *University of Virginia*, Summer 2009--Spring 2010.

Curry Participant Pool Coordinator, *University of Virginia*, Summer 2008- Spring 2009.

Graduate Research Assistant, *University of Virginia*, 2005-2006.

# Teaching

Introduction to Structural Equation Modeling, ERMA 8240, *Auburn University*, Spring 2019 -- Present.

Design and Analysis III, ERMA 8320, *Auburn University*, Fall 2018.

Design and Analysis II, ERMA 7310, *Auburn University*, Spring 2018 -- Present.

Design and Analysis I, ERMA 7300, *Auburn University*, Spring 2017 - Fall 2018 -- Present.

Basic Methods in Education Research, ERMA 7200, *Auburn University*, Fall 2016 -- Present.

Confirmatory Factor Analysis and Scale Reliability, Statistical Programming Workshop, University of Virginia, January, 2016.

Introduction to Multiple Imputation with the `mice` package, Statistical Programming Workshop, University of Virginia, October, 2015.

Introduction to Multilevel Modeling, Statistical Programming Workshop, FOCAL Lab, University of Virginia, July, 2015. 

Introduction to Statistical Programming with R, Statistical Programming Workshop, University of Virginia, Spring, 2015.

Introduction to Linear Models, University of Virginia, Curry Summer Undergraduate Research Program, Summer 2012.

Introduction to Inferential Statistics, University of Virginia, Curry Summer Undergraduate Research Program, Summer 2011.

Child Development, co-instructor, University of Virginia, Spring 2008.

Child Development, teaching assistant, University of Virginia, 2006-2007.

Child Development, co-instructor, Hampton Roads Center, University of Virginia, Spring 2005.

## Professional Activities


Editorial Board for *Interdisciplinary Education and Psychology*.

Reviewer for *Child Development*

Reviewer for *Journal of Abnormal Child Psychology* 

Reviewer for *Early Childhood Research Quarterly* 

Member, *American Statistical Association *

Member, *Society for Research in Child Development*

Member, *American Educational Research Association*

## Invited Workshops

SREE Workshop: Intervention Fidelity -Models, Methods, and Applications, Fall 2014


## Trainings and Conferences Attended

Intensive Longitudinal Methods, Statistical Horizons, October 23-24, 2015

Mediation, Moderation, and Conditional Process Analysis, Andrew F. Hayes, University of Virginia, June 4-5, 2015  

Institute of Education Sciences Summer Research Training Institute: Cluster-Randomized Trials, Northwestern University, July 15-26, 2012

UseR! 2012, Vanderbilt University, June 11-15, 2012

Functional MRI in Clinical Research and Practice: Measurement, Design and Analysis, Carnegie Mellon University/University of Pittsburgh, June 13-17, 2011

Missing Data Workshop, University of Virginia, June 1-7, 2011

Society for Research in Child Development Conference, Montreal, March 31-April 3, 2011

Multi-Modal Neuroimaging Training, Martinos Medical Center, Boston, December 13-17, 2010

Conference on Human Development, New York, April 9-12, 2010


## Software Proficiency

R, Mplus, \LaTeX, SPSS

# Professional Experience

Research Scientist, *University of Virginia*, Charlottesville, VA, 2013-2016.

Postdoctoral Fellow, *University of Virgina*, Charlottesville, VA, 2010-2013.

Team Building Coordinator, *Charlottesville's Challenge Course*, Charlottesville, VA, 2002 - 2004.

Counselor/Intervention Specialist, *Hoover City School System*, Hoover, AL, 1999 - 2002.

Bridges Drug Education Program Instructor, *Hoover City School System*, Hoover, AL, 1999 - 2002.

Independent Contract Work, *Central Alabama*, 1997 - 2002.

Adventure Based Counselor/Case Manager, *Bradford Health Services*, Pelham, AL, 1995 - 1997.

Conflict Resolution Counselor, *Jemison Boy's Ranch*, Jemison, AL, 1993 - 1995.

---
# References

David Grissmer, Research Professor    
CASTL, University of Virginia    
Ruffner Hall 252, PO Box 400877, Charlottesville, VA 22904   
434/243-8200,  dwg7u@virginia.edu
  
Chris Hulleman, Research Associate Professor   
Curry School of Education, University of Virginia   
Center for the Advanced Study of Teaching and Learning    
Ruffner Hall 254, PO Box 400877, Charlottesville VA 22904   
434/943-2437, chris.hulleman@virginia.edu 

Sara Rimm-Kaufman, Professor   
Curry School of Education, University of Virginia    
Ruffner Hall 238, PO Box 800784, Charlottesville VA 22904    
434/982-2863,  ser4x@virginia.edu
---